image:
  file: .gitpod.Dockerfile

tasks:
- name: Start Couchbase
  command:  ./startcb.sh
- name: Log use
  command: curl -s 'https://da-demo-images.s3.amazonaws.com/runItNow_outline.png?couchbase-example=aspnet-quickstart-repo&source=gitpod' > /dev/null
- name: Dotnet setup
  init: |
    sudo wget -q https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb 
    sudo apt-add-repository https://packages.microsoft.com/ubuntu/20.04/prod
    sudo apt-get update
    sudo apt-get install -y sudo apt-transport-https
    sudo apt-get install -y dotnet-sdk-5.0
  command: ./run.sh

# exposed ports
ports:
- port: 5000
  onOpen: ignore 
- port: 5001
  onOpen: open-preview 
- port: 8091
  onOpen: open-browser
- port: 8092-10000
  onOpen: ignore
- port: 4369
  onOpen: ignore

vscode:
  extensions:
    - muhammad-sammy.csharp
